### ISSUE TITLE
The code about synthesis

### ISSUE THREAD

**Issue by LinyeLi60** [Jun-CEN/Open_world_3D_semantic_segmentation#1]
Hi Jun Cen,  congratulations to your paper has been accpeted, very nice work.  I can not found the code about synthesis unknown objects, can you help me?Thank you.

**Comment by Jun-CEN** [comment]
Hi Linye,

Thanks! The code of SemanticKITTI dataset is at: https://github.com/Jun-CEN/Open_world_3D_semantic_segmentation/blob/f7041d6b50b431a510e308d54f359917d7350e26/dataloader/dataset_semantickitti.py#L470-L489

**Comment by LinyeLi60** [comment]
Thank you, the code is intuitive. 

Closed

**Comment by yifliu3** [comment]
Hi Jun Chen, it seems that you're using instances from any classes except for the open classes to synthesize the open data. I'm wondering if my understanding is right.

**Comment by Jun-CEN** [comment]
Yes
