### ISSUE TITLE
Evaluation Scripts for Open-Set Semantic Segmentation

### ISSUE THREAD

**Issue by Yang-Li-2000** [Jun-CEN/Open_world_3D_semantic_segmentation#12]
Table 1 of the paper contains AUPR and AUROC for open-set segmentation. However, the .py files under the semantickitti_scripts folder do not print  AUPR or AUROC at the end of training/evaluation. It seems that they only print per class IoUs for the 20 seen classes at the end of training/evaluation. How can I compute AUPR and AUROC when performing open-set semantic segmentation? Are codes for computing  AUPR and AUROC available?

**Comment by Jun-CEN** [comment]
Hi, 

You can see this [answer](https://github.com/Jun-CEN/Open_world_3D_semantic_segmentation/issues/11#issuecomment-1296715664).

**Comment by Yang-Li-2000** [comment]
Thank you!
