### ISSUE TITLE
How to obtain nuscenes_infos_*.pkl

### ISSUE THREAD

**Issue by jwma0725** [Jun-CEN/Open_world_3D_semantic_segmentation#2]
@Jun-CEN Thanks for your work! 
I want to know how to get the nuscenes_infos_*.pkl(train, val, test).

**Comment by Jun-CEN** [comment]
Hi,
We follow the procedure of [Cylinder3D](https://github.com/xinge008/Cylinder3D/blob/master/NUSCENES-GUIDE.md).

**Comment by jwma0725** [comment]
ok. Thank u!
