### ISSUE TITLE
Which is the initial training code？

### ISSUE THREAD

**Issue by Kamp-Sun** [Jun-CEN/Open_world_3D_semantic_segmentation#20]
Excuse me , I wanna know which the initial training code is . train_cylinder_asym_nuscenes.py or train_cylinder_asym_nuscenes_naive.py ?

**Comment by Jun-CEN** [comment]
Hi,

I am not sure what does the initial code mean here. If it means to train the model with all classes, which is the upper bound in my paper, then it should be train_cylinder_asym_nuscenes.py. If it means to train the model with the known classes without unknown classes, then it should be train_cylinder_asym_nuscenes_naive.py.
