### ISSUE TITLE
problem concerning  the closed-set metrics 

### ISSUE THREAD

**Issue by Daniellli** [Jun-CEN/Open_world_3D_semantic_segmentation#21]
thank you for your such novel  contribution.  

Why the evaluation code of  $mIoU_{old}$,   is calculated   by including  IoU of novel classes (such as other-vehicle for semantic kitti) which are  all equal to zero.  This is inconsistent with the definition of $mIoU_{old}$?   

Do I understand correctly?  Or am i missing something?  please correct me, thank you~

**Comment by Jun-CEN** [comment]
Hi,

The code does show the mIoU of all classes including the unknown classes. However, we report the result of mIoU_old without unknown classes in the paper. As shown in Table 5, the mIoU_old is around 74.4 which clearly doesn't include those unknown classes with 0.
