### ISSUE TITLE
Some questions in dataset_semantickitti.py.

### ISSUE THREAD

**Issue by Kodapsy** [Jun-CEN/Open_world_3D_semantic_segmentation#23]
Hi,
I have been reading your code recently and have some questions about the data processing section to ask you.
First, Why use two methods to get the maximum value in different dimensions(I mean np.max and np.percentile).
https://github.com/Jun-CEN/Open_world_3D_semantic_segmentation/blob/084c341291ae186f174743d8fae5efecea89122f/dataloader/dataset_semantickitti.py#L232-L235
Second, why the grid_size, i.e, outputshape is defined as [480, 360, 32], is there any reference?
Third, If you have time, can you give a simple explanation of the following code? Why is voxel_position calculated this way, and what does the nb_process_label function do?
https://github.com/Jun-CEN/Open_world_3D_semantic_segmentation/blob/084c341291ae186f174743d8fae5efecea89122f/dataloader/dataset_semantickitti.py#L249-L264
I would appreciate it if you could take the time to answer. Wish you a happy life!

**Comment by Jun-CEN** [comment]
Hi,

All these data pre-processing codes are from [Cylinder3D](https://github.com/xinge008/Cylinder3D), and we do not change at all. We simply use Cylinder3D as the backbone and other backbones are also available for our method. You may refer to their paper and codebase.
