### ISSUE TITLE
Point cloud segmentation map in the paper

### ISSUE THREAD

**Issue by 2311762665** [Jun-CEN/Open_world_3D_semantic_segmentation#3]
Hello author, how did you generate the point cloud segmentation map in the paper? Which files need to be downloaded, how to use them, and is there any code reference?

**Comment by Jun-CEN** [comment]
We use the official code of SemanticKITTI for visualization [here](https://github.com/Jun-CEN/semantic_kitti_api/blob/master/visualize.py).
