### ISSUE TITLE
Change in semantic-kitti-upper.yaml

### ISSUE THREAD

**Issue by ChungInchul** [Jun-CEN/Open_world_3D_semantic_segmentation#4]
Hi, Jun Cen. 
First of all thanks for the great work.

I have a small question.

In line 135 of semantic-kitti.yaml
'other-object' was mapped to 'unlabeled' as it is usually ignored for training or evaluation.

However, in line 135 of semantic-kitti-upper.yaml used for training upper bound,
'other-object' was mapped to 'other-vehicle'.

Is there any reason for that?

**Comment by Jun-CEN** [comment]
Hi,

It seems like we should set 'other-object' as 'unlabeled' for the upper bound. I am a little confused about why I changed the setting like that. But it should not influence the final result with a large margin. Upper bound simply means we train the model for the all classes of SemanticKITTI.

**Comment by ChungInchul** [comment]
Thanks!
