### ISSUE TITLE
confused with the strategy of the open-world semantic segmentation

### ISSUE THREAD

**Issue by bithcc** [Jun-CEN/Open_world_3D_semantic_segmentation#6]
Hi, author, thanks for your paper and code, but after reading the paper , i am a little confused that it seems REAL still need new human-made labels to classify the novel object, so how can it handle the static environment when vehicles drive in the open road? Does it just label the novel objects with "unknown" label and still needs human efforts to add more labels of these novel objects to update it, or it can update itself ,classifying novel objects into different classes continuously？ Thanks for your answer.

**Comment by Jun-CEN** [comment]
Hi,

After the model finds the 'unknown' objects, the vehicle is supposed to collect the LIDAR Point Clouds that contains the 'unknown' objects and send the data to the cloud server. The labelers will annotate for the new class on the cloud server and update the model through incremental learning. Then the updated model will be sent to the vehicle. So in our scheme the model cannot update itself without humans' new labels.
